"""empty message

Revision ID: 1696e0bf0eb3
Revises: 9b99555bfa26
Create Date: 2025-04-06 19:13:41.245929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1696e0bf0eb3'
down_revision = '9b99555bfa26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userroles',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role_table.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], )
    )
    with op.batch_alter_table('role_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'user_table', ['user_id'], ['id'])

    op.drop_table('userroles')
    # ### end Alembic commands ###
