"""empty message

Revision ID: 30072f909fc3
Revises: 1696e0bf0eb3
Create Date: 2025-04-06 19:18:23.593048

"""
from alembic import op
import sqlalchemy as sa
from app.extensions import convention


# revision identifiers, used by Alembic.
revision = '30072f909fc3'
down_revision = '1696e0bf0eb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role_table', schema=None, naming_convention=convention) as batch_op:
        batch_op.drop_constraint('fk_role_table_user_id_user_table', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'user_table', ['user_id'], ['id'])

    # ### end Alembic commands ###
