"""empty message

Revision ID: 59fc3e422524
Revises: b9cc70be20ae
Create Date: 2025-05-20 02:27:12.015594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59fc3e422524'
down_revision = 'b9cc70be20ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=30), nullable=False))
        batch_op.drop_column('fname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fname', sa.VARCHAR(length=30), nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
