"""empty message

Revision ID: ab3fbdea990f
Revises: 30072f909fc3
Create Date: 2025-04-06 19:50:01.021620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab3fbdea990f'
down_revision = '30072f909fc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userroles',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role_table.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], )
    )
    with op.batch_alter_table('booking_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'invoice_table', ['invoice_id'], ['id'])
        batch_op.drop_column('room_id')

    with op.batch_alter_table('invoice_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('booking_id')

    with op.batch_alter_table('role_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('room_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capacity', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.Enum('Available', 'Booked', 'Occupied', name='statusenum'), nullable=False))
        batch_op.add_column(sa.Column('booking_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'booking_table', ['booking_id'], ['id'])
        batch_op.drop_column('occupancy')

    with op.batch_alter_table('user_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'address_table', ['address_id'], ['id'])
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=30), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('address_id')

    with op.batch_alter_table('room_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('occupancy', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('booking_id')
        batch_op.drop_column('status')
        batch_op.drop_column('capacity')

    with op.batch_alter_table('role_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'user_table', ['user_id'], ['id'])

    with op.batch_alter_table('invoice_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'booking_table', ['booking_id'], ['id'])

    with op.batch_alter_table('booking_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'room_table', ['room_id'], ['id'])
        batch_op.drop_column('invoice_id')

    op.drop_table('userroles')
    # ### end Alembic commands ###
