"""empty message

Revision ID: df7f2aa7cdc4
Revises: 1968fb1596e5
Create Date: 2025-05-21 05:15:38.507408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df7f2aa7cdc4'
down_revision = '1968fb1596e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invserv',
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice_table.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service_table.id'], )
    )
    with op.batch_alter_table('booking_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'room_table', ['room_id'], ['id'])
        batch_op.drop_column('days')

    with op.batch_alter_table('invoice_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('booking_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'booking_table', ['booking_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('room_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('booking_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('service_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('booking_id')
        batch_op.drop_column('invoice_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('booking_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'booking_table', ['booking_id'], ['id'])
        batch_op.create_foreign_key(None, 'invoice_table', ['invoice_id'], ['id'])

    with op.batch_alter_table('room_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('booking_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'booking_table', ['booking_id'], ['id'])
        batch_op.create_foreign_key(None, 'user_table', ['user_id'], ['id'])

    with op.batch_alter_table('invoice_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_table', ['user_id'], ['id'])
        batch_op.drop_column('booking_id')
        batch_op.drop_column('amount')

    with op.batch_alter_table('booking_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('days', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('room_id')

    op.drop_table('invserv')
    # ### end Alembic commands ###
